//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAP.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="ServiceReference1.TheradPoolWebServiceSoap")]
    public interface TheradPoolWebServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем ReqString из пространства имен http://tempuri.org не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThreadPool.ThreadPoolWebService.GetRId", ReplyAction="*")]
        SOAP.ServiceReference1.GetRIdResponse GetRId(SOAP.ServiceReference1.GetRIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThreadPool.ThreadPoolWebService.GetRId", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAP.ServiceReference1.GetRIdResponse> GetRIdAsync(SOAP.ServiceReference1.GetRIdRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем JobStateResult из пространства имен http://tempuri.org не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThreadPool.ThreadPoolWebService.JobState", ReplyAction="*")]
        SOAP.ServiceReference1.JobStateResponse JobState(SOAP.ServiceReference1.JobStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThreadPool.ThreadPoolWebService.JobState", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAP.ServiceReference1.JobStateResponse> JobStateAsync(SOAP.ServiceReference1.JobStateRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем ResultResult из пространства имен http://tempuri.org не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThreadPool.ThreadPoolWebService.Result", ReplyAction="*")]
        SOAP.ServiceReference1.ResultResponse Result(SOAP.ServiceReference1.ResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThreadPool.ThreadPoolWebService.Result", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAP.ServiceReference1.ResultResponse> ResultAsync(SOAP.ServiceReference1.ResultRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем StatusResult из пространства имен http://tempuri.org не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThreadPool.ThreadPoolWebService.Status", ReplyAction="*")]
        SOAP.ServiceReference1.StatusResponse Status(SOAP.ServiceReference1.StatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThreadPool.ThreadPoolWebService.Status", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAP.ServiceReference1.StatusResponse> StatusAsync(SOAP.ServiceReference1.StatusRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем TestResult из пространства имен http://tempuri.org не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThreadPool.ThreadPoolWebService.Test", ReplyAction="*")]
        SOAP.ServiceReference1.TestResponse Test(SOAP.ServiceReference1.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThreadPool.ThreadPoolWebService.Test", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAP.ServiceReference1.TestResponse> TestAsync(SOAP.ServiceReference1.TestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRId", Namespace="http://tempuri.org", Order=0)]
        public SOAP.ServiceReference1.GetRIdRequestBody Body;
        
        public GetRIdRequest() {
        }
        
        public GetRIdRequest(SOAP.ServiceReference1.GetRIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetRIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReqString;
        
        public GetRIdRequestBody() {
        }
        
        public GetRIdRequestBody(string ReqString) {
            this.ReqString = ReqString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRIdResponse", Namespace="http://tempuri.org", Order=0)]
        public SOAP.ServiceReference1.GetRIdResponseBody Body;
        
        public GetRIdResponse() {
        }
        
        public GetRIdResponse(SOAP.ServiceReference1.GetRIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetRIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRIdResult;
        
        public GetRIdResponseBody() {
        }
        
        public GetRIdResponseBody(string GetRIdResult) {
            this.GetRIdResult = GetRIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JobStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JobState", Namespace="http://tempuri.org", Order=0)]
        public SOAP.ServiceReference1.JobStateRequestBody Body;
        
        public JobStateRequest() {
        }
        
        public JobStateRequest(SOAP.ServiceReference1.JobStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class JobStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long pid;
        
        public JobStateRequestBody() {
        }
        
        public JobStateRequestBody(long pid) {
            this.pid = pid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JobStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JobStateResponse", Namespace="http://tempuri.org", Order=0)]
        public SOAP.ServiceReference1.JobStateResponseBody Body;
        
        public JobStateResponse() {
        }
        
        public JobStateResponse(SOAP.ServiceReference1.JobStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class JobStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JobStateResult;
        
        public JobStateResponseBody() {
        }
        
        public JobStateResponseBody(string JobStateResult) {
            this.JobStateResult = JobStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Result", Namespace="http://tempuri.org", Order=0)]
        public SOAP.ServiceReference1.ResultRequestBody Body;
        
        public ResultRequest() {
        }
        
        public ResultRequest(SOAP.ServiceReference1.ResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class ResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public ResultRequestBody() {
        }
        
        public ResultRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResultResponse", Namespace="http://tempuri.org", Order=0)]
        public SOAP.ServiceReference1.ResultResponseBody Body;
        
        public ResultResponse() {
        }
        
        public ResultResponse(SOAP.ServiceReference1.ResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class ResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ResultResult;
        
        public ResultResponseBody() {
        }
        
        public ResultResponseBody(string ResultResult) {
            this.ResultResult = ResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Status", Namespace="http://tempuri.org", Order=0)]
        public SOAP.ServiceReference1.StatusRequestBody Body;
        
        public StatusRequest() {
        }
        
        public StatusRequest(SOAP.ServiceReference1.StatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class StatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public StatusRequestBody() {
        }
        
        public StatusRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StatusResponse", Namespace="http://tempuri.org", Order=0)]
        public SOAP.ServiceReference1.StatusResponseBody Body;
        
        public StatusResponse() {
        }
        
        public StatusResponse(SOAP.ServiceReference1.StatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class StatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StatusResult;
        
        public StatusResponseBody() {
        }
        
        public StatusResponseBody(string StatusResult) {
            this.StatusResult = StatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test", Namespace="http://tempuri.org", Order=0)]
        public SOAP.ServiceReference1.TestRequestBody Body;
        
        public TestRequest() {
        }
        
        public TestRequest(SOAP.ServiceReference1.TestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestRequestBody {
        
        public TestRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResponse", Namespace="http://tempuri.org", Order=0)]
        public SOAP.ServiceReference1.TestResponseBody Body;
        
        public TestResponse() {
        }
        
        public TestResponse(SOAP.ServiceReference1.TestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class TestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestResult;
        
        public TestResponseBody() {
        }
        
        public TestResponseBody(string TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TheradPoolWebServiceSoapChannel : SOAP.ServiceReference1.TheradPoolWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TheradPoolWebServiceSoapClient : System.ServiceModel.ClientBase<SOAP.ServiceReference1.TheradPoolWebServiceSoap>, SOAP.ServiceReference1.TheradPoolWebServiceSoap {
        
        public TheradPoolWebServiceSoapClient() {
        }
        
        public TheradPoolWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TheradPoolWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TheradPoolWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TheradPoolWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAP.ServiceReference1.GetRIdResponse SOAP.ServiceReference1.TheradPoolWebServiceSoap.GetRId(SOAP.ServiceReference1.GetRIdRequest request) {
            return base.Channel.GetRId(request);
        }
        
        public string GetRId(string ReqString) {
            SOAP.ServiceReference1.GetRIdRequest inValue = new SOAP.ServiceReference1.GetRIdRequest();
            inValue.Body = new SOAP.ServiceReference1.GetRIdRequestBody();
            inValue.Body.ReqString = ReqString;
            SOAP.ServiceReference1.GetRIdResponse retVal = ((SOAP.ServiceReference1.TheradPoolWebServiceSoap)(this)).GetRId(inValue);
            return retVal.Body.GetRIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAP.ServiceReference1.GetRIdResponse> SOAP.ServiceReference1.TheradPoolWebServiceSoap.GetRIdAsync(SOAP.ServiceReference1.GetRIdRequest request) {
            return base.Channel.GetRIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAP.ServiceReference1.GetRIdResponse> GetRIdAsync(string ReqString) {
            SOAP.ServiceReference1.GetRIdRequest inValue = new SOAP.ServiceReference1.GetRIdRequest();
            inValue.Body = new SOAP.ServiceReference1.GetRIdRequestBody();
            inValue.Body.ReqString = ReqString;
            return ((SOAP.ServiceReference1.TheradPoolWebServiceSoap)(this)).GetRIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAP.ServiceReference1.JobStateResponse SOAP.ServiceReference1.TheradPoolWebServiceSoap.JobState(SOAP.ServiceReference1.JobStateRequest request) {
            return base.Channel.JobState(request);
        }
        
        public string JobState(long pid) {
            SOAP.ServiceReference1.JobStateRequest inValue = new SOAP.ServiceReference1.JobStateRequest();
            inValue.Body = new SOAP.ServiceReference1.JobStateRequestBody();
            inValue.Body.pid = pid;
            SOAP.ServiceReference1.JobStateResponse retVal = ((SOAP.ServiceReference1.TheradPoolWebServiceSoap)(this)).JobState(inValue);
            return retVal.Body.JobStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAP.ServiceReference1.JobStateResponse> SOAP.ServiceReference1.TheradPoolWebServiceSoap.JobStateAsync(SOAP.ServiceReference1.JobStateRequest request) {
            return base.Channel.JobStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAP.ServiceReference1.JobStateResponse> JobStateAsync(long pid) {
            SOAP.ServiceReference1.JobStateRequest inValue = new SOAP.ServiceReference1.JobStateRequest();
            inValue.Body = new SOAP.ServiceReference1.JobStateRequestBody();
            inValue.Body.pid = pid;
            return ((SOAP.ServiceReference1.TheradPoolWebServiceSoap)(this)).JobStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAP.ServiceReference1.ResultResponse SOAP.ServiceReference1.TheradPoolWebServiceSoap.Result(SOAP.ServiceReference1.ResultRequest request) {
            return base.Channel.Result(request);
        }
        
        public string Result(long id) {
            SOAP.ServiceReference1.ResultRequest inValue = new SOAP.ServiceReference1.ResultRequest();
            inValue.Body = new SOAP.ServiceReference1.ResultRequestBody();
            inValue.Body.id = id;
            SOAP.ServiceReference1.ResultResponse retVal = ((SOAP.ServiceReference1.TheradPoolWebServiceSoap)(this)).Result(inValue);
            return retVal.Body.ResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAP.ServiceReference1.ResultResponse> SOAP.ServiceReference1.TheradPoolWebServiceSoap.ResultAsync(SOAP.ServiceReference1.ResultRequest request) {
            return base.Channel.ResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAP.ServiceReference1.ResultResponse> ResultAsync(long id) {
            SOAP.ServiceReference1.ResultRequest inValue = new SOAP.ServiceReference1.ResultRequest();
            inValue.Body = new SOAP.ServiceReference1.ResultRequestBody();
            inValue.Body.id = id;
            return ((SOAP.ServiceReference1.TheradPoolWebServiceSoap)(this)).ResultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAP.ServiceReference1.StatusResponse SOAP.ServiceReference1.TheradPoolWebServiceSoap.Status(SOAP.ServiceReference1.StatusRequest request) {
            return base.Channel.Status(request);
        }
        
        public string Status(long id) {
            SOAP.ServiceReference1.StatusRequest inValue = new SOAP.ServiceReference1.StatusRequest();
            inValue.Body = new SOAP.ServiceReference1.StatusRequestBody();
            inValue.Body.id = id;
            SOAP.ServiceReference1.StatusResponse retVal = ((SOAP.ServiceReference1.TheradPoolWebServiceSoap)(this)).Status(inValue);
            return retVal.Body.StatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAP.ServiceReference1.StatusResponse> SOAP.ServiceReference1.TheradPoolWebServiceSoap.StatusAsync(SOAP.ServiceReference1.StatusRequest request) {
            return base.Channel.StatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAP.ServiceReference1.StatusResponse> StatusAsync(long id) {
            SOAP.ServiceReference1.StatusRequest inValue = new SOAP.ServiceReference1.StatusRequest();
            inValue.Body = new SOAP.ServiceReference1.StatusRequestBody();
            inValue.Body.id = id;
            return ((SOAP.ServiceReference1.TheradPoolWebServiceSoap)(this)).StatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAP.ServiceReference1.TestResponse SOAP.ServiceReference1.TheradPoolWebServiceSoap.Test(SOAP.ServiceReference1.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public string Test() {
            SOAP.ServiceReference1.TestRequest inValue = new SOAP.ServiceReference1.TestRequest();
            inValue.Body = new SOAP.ServiceReference1.TestRequestBody();
            SOAP.ServiceReference1.TestResponse retVal = ((SOAP.ServiceReference1.TheradPoolWebServiceSoap)(this)).Test(inValue);
            return retVal.Body.TestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAP.ServiceReference1.TestResponse> SOAP.ServiceReference1.TheradPoolWebServiceSoap.TestAsync(SOAP.ServiceReference1.TestRequest request) {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAP.ServiceReference1.TestResponse> TestAsync() {
            SOAP.ServiceReference1.TestRequest inValue = new SOAP.ServiceReference1.TestRequest();
            inValue.Body = new SOAP.ServiceReference1.TestRequestBody();
            return ((SOAP.ServiceReference1.TheradPoolWebServiceSoap)(this)).TestAsync(inValue);
        }
    }
}
